# Generated by Django 4.2.20 on 2025-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='4A4DF979F31944B69984DE12', editable=False, max_length=24, unique=True),
        ),
    ]
