# Generated by Django 4.2.19 on 2025-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='AF9F8F19EAA842F8A575638A', editable=False, max_length=24, unique=True),
        ),
    ]
