# Generated by Django 4.2.19 on 2025-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='A920CE2DFA4548149F75E2F1', editable=False, max_length=24, unique=True),
        ),
    ]
