# Generated by Django 4.2.19 on 2025-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='DE9BB62AA8D540A997E0B70EEAB34779', editable=False, max_length=32),
        ),
    ]
