# Generated by Django 4.2.20 on 2025-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0E0D4183E74F40138FE7584D', editable=False, max_length=24, unique=True),
        ),
    ]
