# Generated by Django 4.2.19 on 2025-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='304ED4276C474E1383A0F80E', editable=False, max_length=24, unique=True),
        ),
    ]
