# Generated by Django 4.2.20 on 2025-04-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='2C5E4E830D0C4FC1A582285E', editable=False, max_length=24, unique=True),
        ),
    ]
