# Generated by Django 4.2.19 on 2025-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='3BF683F2A3E54599856A91F6', editable=False, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
