# Generated by Django 4.2.19 on 2025-04-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='71E7166EF0784BDFBCF6C267', editable=False, max_length=24, unique=True),
        ),
    ]
