# Generated by Django 4.2.19 on 2025-02-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prints'), (2, 'Paintings'), (3, 'Clothing'), (4, 'Other')], default=4),
        ),
    ]
